baseURL = "https://BlauHimmel.github.io"
languageCode = "en"
title = "BlauHimmel's Blog"
theme = "hugo-nuo"
enableRobotsTXT = true
PygmentsCodeFences = true
canonifyurls = true

# Copyright of your post
copyright = "©Copyright 2018"

# Initial site menu, you can extend menu with content.
[[menu.main]]
  name = "Home"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "Tags"
  weight = 20
  identifier = "tags"
  url = "/tags/"

# Add your own params here
[params]
  author = "BlauHimmel"
  avatar = "/img/avatar.png"
  subtitle = "A lazy programmer who is interested in game developing and computer graphic..."
  paginate = 15

  # Choose your social networks
  email = "461310150@qq.com"
  github = "BlauHimmel"
  twitter = "yu_mi_blau"
